import { createConnection } from 'mysql2/promise';
import * as dotenv from 'dotenv';
dotenv.config();

const scripts = [
  {
    filename: 'SCRIPT_01_magnesium-after-1-month-original.md',
    title: 'Toplux Magnesium — After 1 Month (Original)',
    product: 'Toplux Magnesium',
    hookType: 'After 1 Month',
    hookTier: 'tier1',
    priority: 'HIGH',
    status: 'ready',
    notes: 'Original script — the V18 breakout was built on this structure',
  },
  {
    filename: 'SCRIPT_02_magnesium-after-1-month-v2-coach-ruben.md',
    title: 'Toplux Magnesium — After 1 Month v2 (Coach Ruben Clone)',
    product: 'Toplux Magnesium',
    hookType: 'After 1 Month',
    hookTier: 'tier1',
    priority: 'HIGH',
    status: 'ready',
    notes: 'Coach Ruben clone adaptation — proven structure',
  },
  {
    filename: 'SCRIPT_03_magnesium-after-1-month-v3-stress-dysregulation.md',
    title: 'Toplux Magnesium — Stress Dysregulation Hook',
    product: 'Toplux Magnesium',
    hookType: 'Symptom Checklist',
    hookTier: 'tier1',
    priority: 'HIGH',
    status: 'ready',
    notes: 'Stress dysregulation angle — new hook variant for magnesium',
  },
  {
    filename: 'SCRIPT_04_neuro-gum-instruction-correction-filmed.md',
    title: 'Neuro Gum — Instruction/Correction (Filmed Version)',
    product: 'Neuro Gum',
    hookType: 'Instruction/Correction',
    hookTier: 'tier1',
    priority: 'MEDIUM',
    status: 'ready',
    notes: 'Already filmed — V9 was this script. Needs hook rewrite before refilming.',
  },
  {
    filename: 'SCRIPT_05_neuro-gum-comparison-hook.md',
    title: 'Neuro Gum — Comparison Hook',
    product: 'Neuro Gum',
    hookType: 'Comparison',
    hookTier: 'tier1',
    priority: 'HIGH',
    status: 'ready',
    notes: 'Comparison hook — needs conditional close per V7 pattern',
  },
  {
    filename: 'SCRIPT_06_neuro-gum-version-c-instruction-correction.md',
    title: 'Neuro Gum — Instruction/Correction v3',
    product: 'Neuro Gum',
    hookType: 'Instruction/Correction',
    hookTier: 'tier1',
    priority: 'MEDIUM',
    status: 'ready',
    notes: 'Third iteration — more specific hook than V4',
  },
  {
    filename: 'SCRIPT_07_medicube-deodorant-symptom-reframe.md',
    title: 'Medicube Deodorant — Symptom Reframe',
    product: 'Medicube Deodorant',
    hookType: 'Symptom Checklist',
    hookTier: 'tier1',
    priority: 'HIGH',
    status: 'ready',
    notes: 'Symptom reframe — proven hook type for this product category',
  },
  {
    filename: 'SCRIPT_08_medicube-kojic-instruction-correction.md',
    title: 'Medicube Kojic — Instruction/Correction',
    product: 'Medicube Kojic Serum',
    hookType: 'Instruction/Correction',
    hookTier: 'tier1',
    priority: 'MEDIUM',
    status: 'ready',
    notes: 'Kojic acid mechanism — needs specific hook per framework rules',
  },
  {
    filename: 'SCRIPT_09_medicube-truly-beauty-stack-protocol.md',
    title: 'Medicube + Truly Beauty — Stack Protocol',
    product: 'Medicube + Truly Beauty Stack',
    hookType: 'Stack Protocol',
    hookTier: 'tier1',
    priority: 'MEDIUM',
    status: 'ready',
    notes: 'Two-product stack — targets both underarm problems simultaneously',
  },
  {
    filename: 'SCRIPT_10_medicube-vs-dr-melaxin-comparison.md',
    title: 'Medicube vs Dr. Melaxin — Comparison',
    product: 'Medicube vs Dr. Melaxin Multibalm',
    hookType: 'Comparison',
    hookTier: 'tier1',
    priority: 'HIGH',
    status: 'ready',
    notes: 'Comparison hook — add conditional close per V7 pattern',
  },
  {
    filename: 'SCRIPT_11_medicube-vs-truly-beauty-deodorant-comparison.md',
    title: 'Medicube vs Truly Beauty — Deodorant Comparison',
    product: 'Medicube vs Truly Beauty Deodorant',
    hookType: 'Comparison',
    hookTier: 'tier1',
    priority: 'HIGH',
    status: 'ready',
    notes: 'Comparison hook — add conditional close per V7 pattern',
  },
  {
    filename: 'SCRIPT_12B_dr-melaxin-gifted-collagen-set-rebornic-first.md',
    title: 'Dr. Melaxin Gifted Set — Rebornic First Angle',
    product: 'Dr. Melaxin Gifted Set',
    hookType: 'Expert Verdict',
    hookTier: 'tier1',
    priority: 'MEDIUM',
    status: 'ready',
    notes: 'POST-PRODUCTION NOTE: Rebornic angle — lead with the ingredient, not the brand',
  },
  {
    filename: 'SCRIPT_12_dr-melaxin-gifted-collagen-set-b12-spicule.md',
    title: 'Dr. Melaxin Gifted Set — B12 + Spicule Angle',
    product: 'Dr. Melaxin Gifted Set',
    hookType: 'Ingredient Science',
    hookTier: 'tier1',
    priority: 'MEDIUM',
    status: 'ready',
    notes: 'POST-PRODUCTION NOTE: B12 + spicule mechanism — strong science hook',
  },
  {
    filename: 'SCRIPT_13_dr-melaxin-peel-shot-body-hyperpigmentation.md',
    title: 'Dr. Melaxin Peel Shot — Body Hyperpigmentation',
    product: 'Dr. Melaxin Peel Shot',
    hookType: 'Symptom Checklist',
    hookTier: 'tier1',
    priority: 'HIGH',
    status: 'ready',
    notes: 'Body hyperpigmentation angle — underserved topic with high search intent',
  },
  {
    filename: 'SCRIPT_14_loaded-tea-trend-or-trash.md',
    title: 'Loaded Tea — Trend or Trash',
    product: 'Loaded Tea Shop',
    hookType: 'Trend or Trash',
    hookTier: 'tier1',
    priority: 'HIGH',
    status: 'ready',
    notes: 'V10 was this script — generated $2.40 GMV. Refilm with sharper hook.',
  },
  {
    filename: 'SCRIPT_15_loaded-tea-ingredient-form.md',
    title: 'Loaded Tea — Ingredient Form Hook',
    product: 'Loaded Tea Shop',
    hookType: 'Instruction/Correction',
    hookTier: 'tier1',
    priority: 'MEDIUM',
    status: 'ready',
    notes: 'Ingredient form angle — targets the "right way to take caffeine" structure',
  },
  {
    filename: 'SCRIPT_16_loaded-tea-vs-bloom-comparison.md',
    title: 'Loaded Tea vs Bloom — Comparison',
    product: 'Loaded Tea vs Bloom',
    hookType: 'Comparison',
    hookTier: 'tier1',
    priority: 'HIGH',
    status: 'ready',
    notes: 'V8 was filmed without conditional close — this version adds it. V7 proof: 8,675 views.',
  },
  {
    filename: 'SCRIPT_17_celsius-vs-loaded-tea-comparison.md',
    title: 'Celsius vs Loaded Tea — Comparison',
    product: 'Celsius vs Loaded Tea',
    hookType: 'Comparison',
    hookTier: 'tier1',
    priority: 'HIGH',
    status: 'ready',
    notes: 'Comparison hook — conditional close required',
  },
  {
    filename: 'SCRIPT_18_cerave-invisible-mineral-sunscreen.md',
    title: 'CeraVe Mineral Sunscreen — Instruction/Correction',
    product: 'CeraVe Invisible Mineral Sunscreen',
    hookType: 'Instruction/Correction',
    hookTier: 'tier1',
    priority: 'MEDIUM',
    status: 'ready',
    notes: 'V3 was filmed — 570 views, 5% retention. Hook needs specificity improvement.',
  },
  {
    filename: 'SCRIPT_19_cerave-vs-skin1004-sunscreen-comparison.md',
    title: 'CeraVe vs SKIN1004 — Sunscreen Comparison',
    product: 'CeraVe vs SKIN1004 Sun Serum',
    hookType: 'Comparison',
    hookTier: 'tier1',
    priority: 'HIGH',
    status: 'ready',
    notes: 'Comparison hook — conditional close required',
  },
  {
    filename: 'SCRIPT_20_skin1004-sun-serum-reactive-skin.md',
    title: 'SKIN1004 Sun Serum — Reactive Skin Hook',
    product: 'SKIN1004 Sun Serum',
    hookType: 'Symptom Checklist',
    hookTier: 'tier1',
    priority: 'HIGH',
    status: 'ready',
    notes: 'Reactive skin angle — targets redness, sensitivity, post-procedure skin',
  },
  {
    filename: 'neuro-gum-instruction-correction-comparison.md',
    title: 'Neuro Gum — Instruction/Correction + Comparison Hybrid',
    product: 'Neuro Gum',
    hookType: 'Instruction/Correction',
    hookTier: 'tier1',
    priority: 'MEDIUM',
    status: 'ready',
    notes: 'Hybrid format — instruction hook with comparison close',
  },
];

async function seed() {
  const conn = await createConnection(process.env.DATABASE_URL);
  
  // Clear existing scripts
  await conn.execute('DELETE FROM posted_scripts');
  
  for (const s of scripts) {
    await conn.execute(
      `INSERT INTO posted_scripts (filename, title, product, hook_type, hook_tier, priority, status, notes, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())`,
      [s.filename, s.title, s.product, s.hookType, s.hookTier, s.priority, s.status, s.notes]
    );
  }
  
  console.log(`✅ Seeded ${scripts.length} scripts`);
  await conn.end();
}

seed().catch(console.error);
